/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dorn.view;

import java.util.ArrayList;

/**
 *
 * @author t30r3m4
 */
public class Paredon extends javax.swing.JFrame {

    //boolean[] heroes = new boolean[9];
    //ArrayList<String> listaHeroes = new ArrayList<>();
    int[] selectHeroes = new int[5];
    String[] listHeroes = { "-------", "ALMANOR", "CHOROS", "ELEANOR", "GOR", "GUELIN", "KAERDRAK", "RAGNAR", "RIEL", "VARGEN" };
    String[] listHeroesCopia = { "-------", "ALMANOR", "CHOROS", "ELEANOR", "GOR", "GUELIN", "KAERDRAK", "RAGNAR", "RIEL", "VARGEN" };
    
    
    public Paredon() {
        initComponents();

        //listaHeroes = { "-------", "ALMANOR", "CHOROS", "ELEANOR", "GOR", "GUELIN", "KAERDRAK", "RAGNAR", "RIEL", "VARGEN" };
        initComponent2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpGeneral = new javax.swing.JPanel();
        jpGuardian = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        checkZorkal = new javax.swing.JCheckBox();
        txtZorkal = new javax.swing.JTextField();
        comboZorkal = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jpHeroe = new javax.swing.JPanel();
        jpH1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        check1 = new javax.swing.JCheckBox();
        txt1 = new javax.swing.JTextField();
        combo1 = new javax.swing.JComboBox<>();
        jpH2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        check2 = new javax.swing.JCheckBox();
        txt2 = new javax.swing.JTextField();
        combo2 = new javax.swing.JComboBox<>();
        jpH3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        check3 = new javax.swing.JCheckBox();
        txt3 = new javax.swing.JTextField();
        combo3 = new javax.swing.JComboBox<>();
        jpH4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        check4 = new javax.swing.JCheckBox();
        txt4 = new javax.swing.JTextField();
        combo4 = new javax.swing.JComboBox<>();
        jpH5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        check5 = new javax.swing.JCheckBox();
        txt5 = new javax.swing.JTextField();
        combo5 = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jpAccion = new javax.swing.JPanel();
        jbAceptar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpGeneral.setLayout(new javax.swing.BoxLayout(jpGeneral, javax.swing.BoxLayout.Y_AXIS));

        jpGuardian.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ZORKAL", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bitstream Charter", 1, 18))); // NOI18N
        jpGuardian.setLayout(new java.awt.GridLayout(2, 3));

        jLabel5.setText("Juega");
        jpGuardian.add(jLabel5);

        jLabel4.setText("Jugador");
        jpGuardian.add(jLabel4);

        jLabel6.setText("Guardián");
        jpGuardian.add(jLabel6);

        checkZorkal.setSelected(true);
        checkZorkal.setText("Sí");
        checkZorkal.setEnabled(false);
        jpGuardian.add(checkZorkal);
        jpGuardian.add(txtZorkal);

        comboZorkal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ZORKAL" }));
        jpGuardian.add(comboZorkal);

        jpGeneral.add(jpGuardian);
        jpGeneral.add(jSeparator1);

        jpHeroe.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HÉROES", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bitstream Charter", 1, 18))); // NOI18N
        jpHeroe.setLayout(new java.awt.GridLayout(5, 1));

        jpH1.setLayout(new java.awt.GridLayout(2, 3));

        jLabel3.setText("Juega");
        jpH1.add(jLabel3);

        jLabel1.setText("Jugador 1");
        jpH1.add(jLabel1);

        jLabel2.setText("Héroe");
        jpH1.add(jLabel2);

        check1.setSelected(true);
        check1.setText("Sí");
        check1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check1ActionPerformed(evt);
            }
        });
        jpH1.add(check1);

        txt1.setText("                                               ");
        jpH1.add(txt1);

        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------", "ALMANOR", "CHOROS", "ELEANOR", "GOR", "GUELIN", "KAERDRAK", "RAGNAR", "RIEL", "VARGEN" }));
        combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1ActionPerformed(evt);
            }
        });
        jpH1.add(combo1);

        jpHeroe.add(jpH1);

        jpH2.setLayout(new java.awt.GridLayout(2, 3));

        jLabel7.setText("Juega");
        jpH2.add(jLabel7);

        jLabel8.setText("Jugador 2");
        jpH2.add(jLabel8);

        jLabel9.setText("Héroe");
        jpH2.add(jLabel9);

        check2.setText("Sí");
        check2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check2ActionPerformed(evt);
            }
        });
        jpH2.add(check2);
        jpH2.add(txt2);

        combo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combo2MouseClicked(evt);
            }
        });
        combo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo2ActionPerformed(evt);
            }
        });
        jpH2.add(combo2);

        jpHeroe.add(jpH2);

        jpH3.setLayout(new java.awt.GridLayout(2, 3));

        jLabel10.setText("Juega");
        jpH3.add(jLabel10);

        jLabel11.setText("Jugador 3");
        jpH3.add(jLabel11);

        jLabel12.setText("Héroe");
        jpH3.add(jLabel12);

        check3.setText("Sí");
        check3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check3ActionPerformed(evt);
            }
        });
        jpH3.add(check3);
        jpH3.add(txt3);

        combo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo3ActionPerformed(evt);
            }
        });
        jpH3.add(combo3);

        jpHeroe.add(jpH3);

        jpH4.setLayout(new java.awt.GridLayout(2, 3));

        jLabel13.setText("Juega");
        jpH4.add(jLabel13);

        jLabel14.setText("Jugador 4");
        jpH4.add(jLabel14);

        jLabel15.setText("Héroe");
        jpH4.add(jLabel15);

        check4.setText("Sí");
        check4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check4ActionPerformed(evt);
            }
        });
        jpH4.add(check4);
        jpH4.add(txt4);

        combo4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo4ActionPerformed(evt);
            }
        });
        jpH4.add(combo4);

        jpHeroe.add(jpH4);

        jpH5.setLayout(new java.awt.GridLayout(2, 3));

        jLabel16.setText("Juega");
        jpH5.add(jLabel16);

        jLabel17.setText("Jugador 5");
        jpH5.add(jLabel17);

        jLabel18.setText("Héroe");
        jpH5.add(jLabel18);

        check5.setText("Sí");
        check5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check5ActionPerformed(evt);
            }
        });
        jpH5.add(check5);
        jpH5.add(txt5);

        combo5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo5ActionPerformed(evt);
            }
        });
        jpH5.add(combo5);

        jpHeroe.add(jpH5);

        jpGeneral.add(jpHeroe);
        jpGeneral.add(jSeparator2);

        jpAccion.setLayout(new java.awt.GridLayout(2, 0));

        jbAceptar.setText("Aceptar");
        jpAccion.add(jbAceptar);

        jbSalir.setText("Cancelar");
        jpAccion.add(jbSalir);

        jpGeneral.add(jpAccion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void check2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check2ActionPerformed
        if(check2.isSelected()){
            txt2.setEnabled(true);
            combo2.setEnabled(true);
        }else{
            txt2.setText("");
            combo2.setSelectedIndex(0);
            txt2.setEnabled(false);
            combo2.setEnabled(false);            
        }
    }//GEN-LAST:event_check2ActionPerformed

    private void check1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check1ActionPerformed
        if(check1.isSelected()){
            txt1.setEnabled(true);
            combo1.setEnabled(true);
        }else{
            txt1.setText("");
            combo1.setSelectedIndex(0);
            txt1.setEnabled(false);
            combo1.setEnabled(false);            
        }
    }//GEN-LAST:event_check1ActionPerformed

    private void check3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check3ActionPerformed
        if(check3.isSelected()){
            txt3.setEnabled(true);
            combo3.setEnabled(true);
        }else{
            txt3.setText("");
            combo3.setSelectedIndex(0);
            txt3.setEnabled(false);
            combo3.setEnabled(false);            
        }
    }//GEN-LAST:event_check3ActionPerformed

    private void check4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check4ActionPerformed
        if(check4.isSelected()){
            txt4.setEnabled(true);
            combo4.setEnabled(true);
        }else{
            txt4.setText("");
            combo4.setSelectedIndex(0);
            txt4.setEnabled(false);
            combo4.setEnabled(false);            
        }
    }//GEN-LAST:event_check4ActionPerformed

    private void check5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check5ActionPerformed
        if(check5.isSelected()){
            txt5.setEnabled(true);
            combo5.setEnabled(true);
        }else{
            txt5.setText("");
            combo5.setSelectedIndex(0);
            txt5.setEnabled(false);
            combo5.setEnabled(false);            
        }
    }//GEN-LAST:event_check5ActionPerformed

    private void combo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo2MouseClicked

    }//GEN-LAST:event_combo2MouseClicked

    private void combo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo3ActionPerformed
        //Libera
        //int old = selectHeroes[3-1];
        //listHeroes[old] = listHeroesCopia[old];
        if(combo3.getSelectedIndex()!=0){            
            //Anota
            listHeroes[combo3.getSelectedIndex()]="xxx";
            selectHeroes[3-1]=combo3.getSelectedIndex();
        }
        actualizarComboBox(3);
    }//GEN-LAST:event_combo3ActionPerformed

    private void combo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo2ActionPerformed
        if(combo2.getSelectedIndex()!=0){            
            //Anota
            listHeroes[combo2.getSelectedIndex()]="xxx";
            selectHeroes[2-1]=combo2.getSelectedIndex();
        }
        actualizarComboBox(3);
    }//GEN-LAST:event_combo2ActionPerformed

    private void combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1ActionPerformed

        /*if(combo1.getSelectedIndex()!=0){  
            //Libera
            int old = selectHeroes[0];
            listHeroes[old] = listHeroesCopia[old];            
            //Anota
            selectHeroes[0]=combo1.getSelectedIndex();
            System.out.println("----Actualiza");
            for(int a:selectHeroes){
                System.out.println(a);
            }
            listHeroes[combo1.getSelectedIndex()]=listHeroes[0];
            actualizarComboBox(1);
        }else{
            
        }*/
        
    }//GEN-LAST:event_combo1ActionPerformed

    private void combo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo4ActionPerformed
       /* //Libera
        int old = selectHeroes[4-1];
        listHeroes[old] = listHeroesCopia[old];
        if(combo4.getSelectedIndex()!=0){            
            //Anota
            listHeroes[combo4.getSelectedIndex()]=listHeroes[0];
            selectHeroes[4-1]=combo4.getSelectedIndex();
        }
        actualizarComboBox(4);*/
    }//GEN-LAST:event_combo4ActionPerformed

    private void combo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo5ActionPerformed
        /*if(combo5.getSelectedIndex()!=0){
            System.out.println(combo5.getSelectedItem());
        }else{
            System.out.println("Combo 5 Default");
        }*/
    }//GEN-LAST:event_combo5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paredon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paredon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paredon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paredon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paredon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox check1;
    private javax.swing.JCheckBox check2;
    private javax.swing.JCheckBox check3;
    private javax.swing.JCheckBox check4;
    private javax.swing.JCheckBox check5;
    private javax.swing.JCheckBox checkZorkal;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JComboBox<String> combo2;
    private javax.swing.JComboBox<String> combo3;
    private javax.swing.JComboBox<String> combo4;
    private javax.swing.JComboBox<String> combo5;
    private javax.swing.JComboBox<String> comboZorkal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JPanel jpAccion;
    private javax.swing.JPanel jpGeneral;
    private javax.swing.JPanel jpGuardian;
    private javax.swing.JPanel jpH1;
    private javax.swing.JPanel jpH2;
    private javax.swing.JPanel jpH3;
    private javax.swing.JPanel jpH4;
    private javax.swing.JPanel jpH5;
    private javax.swing.JPanel jpHeroe;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txtZorkal;
    // End of variables declaration//GEN-END:variables

    private void initComponent2() {

        txt2.setEnabled(false);
        txt3.setEnabled(false);
        txt4.setEnabled(false);
        txt5.setEnabled(false);
        
        combo2.setEnabled(false);
        combo3.setEnabled(false);
        combo4.setEnabled(false);
        combo5.setEnabled(false);
        actualizarComboBox();

    }
    public void actualizarComboBox(){
        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(listHeroes));
        combo2.setModel(new javax.swing.DefaultComboBoxModel<>(listHeroes));
        combo3.setModel(new javax.swing.DefaultComboBoxModel<>(listHeroes));
        combo4.setModel(new javax.swing.DefaultComboBoxModel<>(listHeroes));
        combo5.setModel(new javax.swing.DefaultComboBoxModel<>(listHeroes));
    }
    public void actualizarComboBox(int exc){    
        switch (exc) {
            case 1:
                combo2.setModel(new javax.swing.DefaultComboBoxModel<>(listHeroes));
                combo3.setModel(new javax.swing.DefaultComboBoxModel<>(listHeroes));
                combo4.setModel(new javax.swing.DefaultComboBoxModel<>(listHeroes));
                combo5.setModel(new javax.swing.DefaultComboBoxModel<>(listHeroes));
                break;
            case 2:
                combo1.setModel(new javax.swing.DefaultComboBoxModel<>(listHeroes));
                combo3.setModel(new javax.swing.DefaultComboBoxModel<>(listHeroes));
                combo4.setModel(new javax.swing.DefaultComboBoxModel<>(listHeroes));
                combo5.setModel(new javax.swing.DefaultComboBoxModel<>(listHeroes));
                break;
            case 3:
                combo1.setModel(new javax.swing.DefaultComboBoxModel<>(listHeroes));
                combo2.setModel(new javax.swing.DefaultComboBoxModel<>(listHeroes));
                combo4.setModel(new javax.swing.DefaultComboBoxModel<>(listHeroes));
                combo5.setModel(new javax.swing.DefaultComboBoxModel<>(listHeroes));
                break;
            case 4:
                combo1.setModel(new javax.swing.DefaultComboBoxModel<>(listHeroes));
                combo2.setModel(new javax.swing.DefaultComboBoxModel<>(listHeroes));
                combo3.setModel(new javax.swing.DefaultComboBoxModel<>(listHeroes));
                combo5.setModel(new javax.swing.DefaultComboBoxModel<>(listHeroes));
                break;
            case 5:
                combo1.setModel(new javax.swing.DefaultComboBoxModel<>(listHeroes));
                combo2.setModel(new javax.swing.DefaultComboBoxModel<>(listHeroes));
                combo3.setModel(new javax.swing.DefaultComboBoxModel<>(listHeroes));
                combo4.setModel(new javax.swing.DefaultComboBoxModel<>(listHeroes));
                break;
            default:
                break;
        }
        System.out.println("----Actualiza");
        for(int a:selectHeroes){
            System.out.println(a);
        }
        combo1.setSelectedIndex(selectHeroes[0]);
        combo2.setSelectedIndex(selectHeroes[1]);
        combo3.setSelectedIndex(selectHeroes[2]);
        combo4.setSelectedIndex(selectHeroes[3]);
        combo5.setSelectedIndex(selectHeroes[4]);
        
    }
}
